[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tae"
version = "1.2.0"
description = "Text Anonymization Evaluator (TAE)"
authors = [
    { name = "Benet Manzanares-Salor", email = "benet.manzanares@urv.cat" }
]
maintainers = [
    { name = "Benet Manzanares-Salor", email = "benet.manzanares@urv.cat" }
]
keywords = ["text anonymization", "evaluation", "privacy", "utility", "nlp", "text processing", "language processing"]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Text Processing",
    "Topic :: Text Processing :: Linguistic",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

dependencies = [
    "torch >= 2.11.0, < 3.0.0",
    "transformers >= 4.42.4", 
    "sentence-transformers >= 2.2.2",
    "accelerate >= 0.33.0",
    "spacy >= 3.7.5",
    "intervaltree >= 3.2.1",
    "numpy >= 2.1.0",
    "pandas >= 2.2.0",
    "scikit-learn >= 1.5.0",
    "scipy >= 1.13.0",
    "tqdm >= 4.66.0",
    "en-core-web-lg @ https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl",
    "en-core-web-md @ https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.8.0/en_core_web_md-3.8.0-py3-none-any.whl",
]

[project.urls]
repository = "https://github.com/BenetManzanaresSalor/TAE"

[tool.setuptools.packages.find]
include = ["tae*"]